# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('mode', models.BooleanField(default=True)),
                ('x_path', models.TextField(default='100,', null=True)),
                ('y_path', models.TextField(default='400,', null=True)),
                ('finished', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to=b'')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
